import { ThemeBase } from '@/types';

export const useThemeDefaults = () => {
  const defaultTheme: ThemeBase = {
    primary_color: '#ffffff',
    secondary_color: '#000000',
    accent_color: '#ff4081',
    text_primary_color: '#333333',
    text_secondary_color: '#666666',
    text_link_color: '#1e88e5',
    text_heading_color: '#212121',
    neon_cyan: '#00ffff',
    neon_pink: '#ff00ff',
    neon_purple: '#800080',
    font_family_heading: 'Arial, sans-serif',
    font_family_body: 'Georgia, serif',
    font_size_base: '16px',
    font_weight_normal: '400',
    font_weight_bold: '700',
    line_height_base: '1.5',
    letter_spacing: '0.05em',
    border_radius: '4px',
    spacing_unit: '8px',
    transition_duration: '0.3s',
    shadow_color: 'rgba(0, 0, 0, 0.2)',
    hover_scale: '1.05',
    box_shadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    backdrop_blur: '10px',
    theme_mode: 'light',
    transition_type: 'fade',
    animations_enabled: true,
    default_animation_duration: 300,
    real_time_toggle: true,
    component_type: 'layout',
    preview_preferences: {
      real_time_updates: true,
      animation_enabled: true,
      glass_effect_level: 'medium',
      update_debounce_ms: 100,
    },
    parent_theme_id: null,
    inheritance_strategy: 'merge',
    inherited_settings: {},
    site_title: 'Default Site Title',
    tagline: 'Default Tagline',
    logo_url: '',
    favicon_url: '',
    updated_at: new Date().toISOString(),
    updated_by: 'system',
    created_at: new Date().toISOString(),
    created_by: 'system',
    colors: {
      primary: '#ffffff',
      secondary: '#000000',
      accent: '#ff4081',
      text: {
        primary: '#333333',
        secondary: '#666666',
        link: '#1e88e5',
        heading: '#212121',
      },
      neon: {
        cyan: '#00ffff',
        pink: '#ff00ff',
        purple: '#800080',
      },
    },
    typography: {
      fontFamilyHeading: 'Arial, sans-serif',
      fontFamilyBody: 'Georgia, serif',
      fontSizeBase: '16px',
      fontWeightNormal: '400',
      fontWeightBold: '700',
      lineHeightBase: '1.5',
      letterSpacing: '0.05em',
    },
    effects: {
      borderRadius: '4px',
      shadowColor: 'rgba(0, 0, 0, 0.2)',
      hoverScale: '1.05',
      boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
      backdropBlur: '10px',
    },
    spacing: {
      unit: '8px',
    },
    animations: {
      enabled: true,
      duration: 300,
    },
  };

  return defaultTheme;
};
