import { ThemeBase } from '@/types';

export type ThemeConfigurationTable = {
  id: string;
  site_title: string;
  tagline?: string;
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  text_primary_color: string;
  text_secondary_color: string;
  text_link_color: string;
  text_heading_color: string;
  neon_cyan: string;
  neon_pink: string;
  neon_purple: string;
  font_family_heading: string;
  font_family_body: string;
  font_size_base: string;
  font_weight_normal: string;
  font_weight_bold: string;
  line_height_base: string;
  letter_spacing: string;
  border_radius: string;
  spacing_unit: string;
  transition_duration: string;
  shadow_color: string;
  hover_scale: string;
  box_shadow: string;
  backdrop_blur: string;
  theme_mode: ThemeBase['theme_mode'];
  transition_type: ThemeBase['transition_type'];
  animations_enabled: boolean;
  default_animation_duration: number;
  preview_preferences: {
    real_time_updates: boolean;
    animation_enabled: boolean;
    glass_effect_level: 'low' | 'medium' | 'high';
    update_debounce_ms: number;
  };
  parent_theme_id?: string | null;
  inheritance_strategy: 'merge' | 'override' | 'replace';
  inherited_settings: Record<string, unknown>;
};
